POST http://localhost:4000/login
Content-Type : application/json

{
    "username":"kyle"
}

###

GET  http://localhost:3000/posts
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTY2NzkzNzE1NiwiZXhwIjoxNjY3OTM3MTgxfQ.u-Ib1xG1KsYpGkM1OtWVAF-EzekDT1ny9o3D5HULXz8

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTY2NzkzNzEyN30.tQEedvmGW3XjVEY2hgXwrPOynratKht4fY_7Cihz5Wc"
}

###
DELETE  http://localhost:4000/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3lsZSIsImlhdCI6MTY2NzkzNzEyN30.tQEedvmGW3XjVEY2hgXwrPOynratKht4fY_7Cihz5Wc"
}